#!/usr/bin/env python3
"""Guard generated distribution patches against lost work.

Each release overlay has a committed file manifest. The v0.24 ship lineage
also records the exact source-branch commit and byte-verifies the patch when
the fork clone is available. The v0.25 candidate is a frozen overlay, so its
``--update`` mode refreshes only the manifest; it never rewrites the patch.

Usage: python3 tools/check_patch_files.py [--version 0.24.0|0.25.0] [--update]
"""

import argparse
import os
import re
import subprocess
import sys


ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RELEASES = {
    "0.24.0": {
        "patch": "vllm-moet-v0.24.0.patch",
        "manifest": "FILES.txt",
        "source": "SOURCE.txt",
        "branch": "moet-v0.24.0",
        "base_tag": "v0.24.0",
        "fork_candidates": [
            "/workspace/vllm-v0.24.0",
            "/root/workspace/vllm-v0.24.0",
        ],
    },
    "0.25.0": {
        "patch": "vllm-moet-v0.25.0.patch",
        "manifest": "FILES-v025.txt",
        "source": None,
        "branch": None,
        "base_tag": "v0.25.0",
        "fork_candidates": [],
    },
}

_SHA_RE = re.compile(r"^[0-9a-f]{40}$")
# ``index <old>..<new>[ <mode>]`` uses the local core.abbrev setting. Ignore
# those hashes so byte verification tracks content rather than git config.
_INDEX_RE = re.compile(rb"^index [0-9a-f]+\.\.[0-9a-f]+( \d+)?$")


def git(repo: str, *args: str, check: bool = True) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["git", "-C", repo, *args], capture_output=True, check=check
    )


def release_paths(release: dict) -> tuple[str, str, str | None]:
    patch_path = os.path.join(ROOT, "patch", release["patch"])
    manifest_path = os.path.join(ROOT, "patch", release["manifest"])
    source_path = (
        os.path.join(ROOT, "patch", release["source"])
        if release["source"]
        else None
    )
    return patch_path, manifest_path, source_path


def manifest_header(version: str, release: dict) -> str:
    return f"""\
# Files touched by patch/{release['patch']} (sorted; generated by
# tools/check_patch_files.py --version {version} --update, verified by CI
# bench-lint). A file DISAPPEARING from this list means work was dropped by
# regeneration; restore it in the source branch instead of hiding the loss.
"""


def source_header(release: dict) -> str:
    return f"""\
# The vllm fork-branch commit patch/{release['patch']} was generated
# from (branch {release['branch']}, diffed against the {release['base_tag']} tag).
# Written by tools/check_patch_files.py --update, byte-verified wherever a fork
# clone is available (dev boxes; CI has none). Regenerations only move this
# FORWARD along the branch - see AGENTS.md. Never edit by hand.
"""


def patch_files(patch_path: str) -> list[str]:
    files = set()
    with open(patch_path) as patch_file:
        for line in patch_file:
            match = re.match(r"^diff --git a/(\S+) b/(\S+)", line)
            if match:
                files.add(match.group(2))
    return sorted(files)


def listed_files(manifest_path: str) -> list[str]:
    if not os.path.exists(manifest_path):
        return []
    with open(manifest_path) as manifest_file:
        return sorted(
            line.strip()
            for line in manifest_file
            if line.strip() and not line.startswith("#")
        )


def read_source(source_path: str) -> str | None:
    if not os.path.exists(source_path):
        return None
    with open(source_path) as source_file:
        for line in source_file:
            line = line.strip()
            if line and not line.startswith("#"):
                if not _SHA_RE.match(line):
                    sys.exit(
                        f"{os.path.relpath(source_path, ROOT)} is malformed "
                        f"({line!r} is not a full sha) - regenerate via --update"
                    )
                return line
    return None


def normalized(diff: bytes) -> list[bytes]:
    return [b"index" if _INDEX_RE.match(line) else line for line in diff.split(b"\n")]


def find_fork(release: dict) -> str | None:
    branch = release["branch"]
    if not branch:
        return None
    env = os.environ.get("VLLM_MOET_FORK")
    candidates = [env] if env else release["fork_candidates"]
    for candidate in candidates:
        if not candidate or not os.path.isdir(candidate):
            continue
        if (
            git(
                candidate,
                "rev-parse",
                "--verify",
                "--quiet",
                branch,
                check=False,
            ).returncode
            == 0
        ):
            return candidate
    return None


def check_files(patch_path: str, manifest_path: str, manifest_name: str) -> int:
    actual = patch_files(patch_path)
    expected = listed_files(manifest_path)
    missing = sorted(set(expected) - set(actual))
    extra = sorted(set(actual) - set(expected))
    if not missing and not extra:
        print(f"{manifest_name}: patch file list OK ({len(actual)} files)")
        return 0
    if missing:
        print(
            f"FILES IN {manifest_name} BUT MISSING FROM THE PATCH - a line "
            "of work was dropped by a regeneration (merge it into the vllm "
            "fork branch, do not update the list to paper over it):"
        )
        for name in missing:
            print(f"  - {name}")
    if extra:
        print(
            f"files in the patch but not in {manifest_name} (new work - run "
            "--update and commit the list together with the patch):"
        )
        for name in extra:
            print(f"  + {name}")
    return 1


def check_source(
    release: dict, patch_path: str, source_path: str, fork: str | None
) -> int:
    sha = read_source(source_path)
    source_name = os.path.relpath(source_path, ROOT)
    if sha is None:
        print(
            f"{source_name} missing - the patch has no recorded source commit; "
            "regenerate via --update (see AGENTS.md)"
        )
        return 1
    if fork is None:
        print(
            f"patch source: no fork clone here - byte-verify skipped "
            f"({source_name} records {sha[:12]})"
        )
        return 0
    if git(fork, "cat-file", "-e", sha + "^{commit}", check=False).returncode != 0:
        print(
            f"patch source: recorded commit {sha[:12]} is unknown in the fork "
            f"clone at {fork} - fetch the fork remotes and retry"
        )
        return 1
    regenerated = git(fork, "diff", release["base_tag"], sha).stdout
    with open(patch_path, "rb") as patch_file:
        committed = patch_file.read()
    if normalized(regenerated) == normalized(committed):
        print(
            f"patch source OK: byte-identical to `git diff "
            f"{release['base_tag']} {sha[:12]}` in {fork}"
        )
        return 0
    print(
        f"THE PATCH IS NOT THE GENERATION OF ITS RECORDED SOURCE ({sha[:12]}): "
        "it was hand-edited, or regenerated outside --update. Work that exists "
        "only in the patch file must be merged into the fork branch FIRST, then "
        "regenerate with --update. Never hand-edit the patch (see AGENTS.md)."
    )
    return 1


def check_release(version: str, release: dict, fork: str | None) -> int:
    patch_path, manifest_path, source_path = release_paths(release)
    result = check_files(patch_path, manifest_path, release["manifest"])
    if source_path:
        result |= check_source(release, patch_path, source_path, fork)
    return result


def update_manifest(version: str, release: dict) -> int:
    patch_path, manifest_path, _ = release_paths(release)
    files = patch_files(patch_path)
    with open(manifest_path, "w") as manifest_file:
        manifest_file.write(manifest_header(version, release))
        manifest_file.write("\n".join(files) + "\n")
    print(f"{release['manifest']} updated: {len(files)} files")
    return check_files(patch_path, manifest_path, release["manifest"])


def update_sourced_release(version: str, release: dict, fork: str | None) -> int:
    if fork is None:
        candidates = release["fork_candidates"]
        sys.exit(
            f"--update needs the vllm fork clone (branch {release['branch']}); "
            f"set VLLM_MOET_FORK or clone to {candidates[0]}"
        )
    patch_path, manifest_path, source_path = release_paths(release)
    assert source_path is not None

    remote_ref = "refs/remotes/fork/" + release["branch"]
    if (
        git(fork, "rev-parse", "--verify", "--quiet", remote_ref, check=False).returncode
        == 0
        and git(
            fork,
            "merge-base",
            "--is-ancestor",
            remote_ref,
            release["branch"],
            check=False,
        ).returncode
        != 0
    ):
        sys.exit(
            f"refusing: fork/{release['branch']} is not an ancestor of the "
            f"local {release['branch']} - the local branch is missing pushed "
            "commits; merge/pull in the fork clone first"
        )

    new_sha = git(fork, "rev-parse", release["branch"]).stdout.decode().strip()
    old_sha = read_source(source_path)
    if old_sha and old_sha != new_sha:
        if git(fork, "cat-file", "-e", old_sha + "^{commit}", check=False).returncode:
            sys.exit(
                f"refusing: recorded source {old_sha[:12]} is unknown in the "
                "fork clone - fetch the fork remotes first"
            )
        if (
            git(
                fork,
                "merge-base",
                "--is-ancestor",
                old_sha,
                new_sha,
                check=False,
            ).returncode
            != 0
        ):
            sys.exit(
                f"refusing: recorded source {old_sha[:12]} is NOT an ancestor "
                f"of the {release['branch']} tip {new_sha[:12]} - regenerating "
                "would roll back shipped work; merge the missing line into the "
                "branch first (see AGENTS.md)"
            )

    relative_patch = os.path.relpath(patch_path, ROOT)
    patch_was_dirty = (
        git(ROOT, "diff", "--quiet", "--", relative_patch, check=False).returncode
        != 0
    )
    diff = git(fork, "diff", release["base_tag"], new_sha).stdout
    if b"diff --git" not in diff:
        sys.exit(
            f"refusing: `git diff {release['base_tag']} {release['branch']}` "
            "came back empty - wrong clone or branch?"
        )
    with open(patch_path, "wb") as patch_file:
        patch_file.write(diff)
    files = patch_files(patch_path)
    with open(manifest_path, "w") as manifest_file:
        manifest_file.write(manifest_header(version, release))
        manifest_file.write("\n".join(files) + "\n")
    with open(source_path, "w") as source_file:
        source_file.write(source_header(release))
        source_file.write(new_sha + "\n")
    if patch_was_dirty:
        print(
            "note: patch/ had UNCOMMITTED edits and they were just overwritten "
            "by this regeneration - if that was a line of work, it must land "
            "on the fork branch, not in the patch"
        )
    print(
        f"patch regenerated from {release['branch']} @ {new_sha[:12]} "
        f"({len(files)} files)"
        + (f" [source {old_sha[:12]} -> {new_sha[:12]}]" if old_sha else "")
    )
    print(
        "now REVIEW `git diff patch/` (vanishing manifest entries mean "
        "someone's work is not on the branch) and commit the patch, manifest, "
        "and source fingerprint together"
    )
    return check_release(version, release, fork)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--version", choices=sorted(RELEASES), default="0.24.0")
    parser.add_argument("--update", action="store_true")
    args = parser.parse_args()

    release = RELEASES[args.version]
    fork = find_fork(release)
    if args.update:
        if release["source"]:
            return update_sourced_release(args.version, release, fork)
        return update_manifest(args.version, release)
    return check_release(args.version, release, fork)


if __name__ == "__main__":
    sys.exit(main())
