#!/usr/bin/env python3
"""Guard against patch regenerations that silently drop a line of work.

The distribution patches are GENERATED artifacts: `git diff <tag> HEAD` from
the corresponding vLLM source branch. Twice now a
feature line landed in the patch without its source commits reaching the
fork branch, and the next regeneration-from-branch silently erased it
(caught by hand both times — Kimi-K2.7, then the DSpark backport).

This check makes that failure loud: each release has a committed, sorted list
of files its patch is expected to touch. CI fails when a patch and its list
disagree IN EITHER DIRECTION, so a regeneration that loses files cannot land
without an explicit, reviewable manifest edit.

Regeneration procedure (also in each manifest header):
    cd <vllm source branch>
    git diff v0.25.0 HEAD > <vLLM-Moet>/patch/vllm-moet-v0.25.0.patch
    python3 tools/check_patch_files.py --version 0.25.0 --update
    # entries VANISHING from the manifest = someone's line of work is not in
    # the fork branch — merge it there first, never ship the loss.

Usage: python3 tools/check_patch_files.py [--version 0.24.0|0.25.0] [--update]
"""

import argparse
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RELEASES = {
    "0.24.0": ("vllm-moet-v0.24.0.patch", "FILES.txt"),
    "0.25.0": ("vllm-moet-v0.25.0.patch", "FILES-v025.txt"),
}


def patch_files(patch_path: str) -> list[str]:
    files = set()
    with open(patch_path) as f:
        for line in f:
            m = re.match(r"^diff --git a/(\S+) b/(\S+)", line)
            if m:
                files.add(m.group(2))
    return sorted(files)


def listed_files(list_path: str) -> list[str]:
    if not os.path.exists(list_path):
        return []
    with open(list_path) as f:
        return sorted(
            line.strip() for line in f if line.strip() and not line.startswith("#")
        )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--version", choices=sorted(RELEASES), default="0.24.0")
    parser.add_argument("--update", action="store_true")
    args = parser.parse_args()

    patch_name, list_name = RELEASES[args.version]
    patch_path = os.path.join(ROOT, "patch", patch_name)
    list_path = os.path.join(ROOT, "patch", list_name)
    header = f"""\
# Files touched by patch/{patch_name} (sorted; generated by
# tools/check_patch_files.py --version {args.version} --update, verified by CI
# bench-lint). A file DISAPPEARING from this list means work was dropped by
# regeneration; restore it in the source branch instead of hiding the loss.
"""

    actual = patch_files(patch_path)
    if args.update:
        with open(list_path, "w") as f:
            f.write(header)
            f.write("\n".join(actual) + "\n")
        print(f"{list_name} updated: {len(actual)} files")
        return 0
    expected = listed_files(list_path)
    missing = sorted(set(expected) - set(actual))
    extra = sorted(set(actual) - set(expected))
    if not missing and not extra:
        print(f"patch file list OK ({len(actual)} files)")
        return 0
    if missing:
        print(
            f"FILES IN {list_name} BUT MISSING FROM THE PATCH — a line of "
            "work was dropped by a regeneration (merge it into the vllm "
            "fork branch, do not update the list to paper over it):"
        )
        for f in missing:
            print(f"  - {f}")
    if extra:
        print(
            f"files in the patch but not in {list_name} (new work — run "
            "--update and commit the list together with the patch):"
        )
        for f in extra:
            print(f"  + {f}")
    return 1


if __name__ == "__main__":
    sys.exit(main())
